module HobbiesModule

    def favourite_military_branch
        [
        "Infantry",
        "Air Defense Artillery",
        "Armor",
        "Aviation",
        "Corps of Engineers",
        "Field Artillery",
        "Special Forces",
        "Chemical Corps",
        "Signal Corps",
        "Military Intelligence Corps",
        "Military Police Corps",
        "Adjutant General's Corps",
        "Finance Corps",
        "Ordnance Corps",
        "Quartermaster Corps",
        "Transportation Corps",
        "Judge Advocate Generals Corps",
        "Chaplain Corps",
        "Medical Corps",
        "Medical Service Corps",
        "Dental Corps",
        "Veterinary Corps",
        "Army Medical Specialist Corps",
        "Army Nurse Corps"
        ]
    end
    
    def hobbies
        [
            "3D printing",
            "Acroyoga",
            "Acting[2]",
            "Amateur Radio",
            "Animation",
            "Anime",
            "Aquascaping",
            "Art",
            "Astrology",
            "Astronomy",
            "Baking",
            "Barbershop Music",
            "Bartending",
            "Basket Weaving",
            "Baton twirling[3]",
            "Beatboxing",
            "Beer tasting",
            "Bell ringing",
            "Binge watching",
            "Blacksmith",
            "Blogging",
            "Bonsai[4]",
            "Board/tabletop games[5]",
            "Book discussion clubs",
            "Book restoration",
            "Bowling",
            "Brazilian jiu-jitsu[6]",
            "Breadmaking",
            "Building",
            "Bullet journaling",
            "Butchering",
            "Calligraphy[7]",
            "Candle making[8]",
            "Candy making",
            "Car spotting",
            "Car fixing & building",
            "Card games",
            "Cardistry",
            "Ceramics",
            "Chatting",
            "Cheesemaking",
            "Chess",
            "Cleaning",
            "Clothesmaking",
            "Coffee roasting",
            "Collecting",
            "Coloring[9]",
            "Communication",
            "Community activism",
            "Computer programming[10]",
            "Confectionery",
            "Conlanging",
            "Construction",
            "Cooking[11]",
            "Cosplaying[12]",
            "Couponing",
            "Craft",
            "Creative writing[13]",
            "Crocheting[14]",
            "Cross-stitch",
            "Crossword puzzles",
            "Cryptography[15]",
            "Cue sports",
            "Dance[16]",
            "Decorating",
            "Decorative birds",
            "Digital arts[17]",
            "Dining",
            "Diorama",
            "Distro Hopping",
            "Diving",
            "Djembe",
            "DJing",
            "Do it yourself[18]",
            "Drama[19]",
            "Drawing[20]",
            "Editing",
            "Electronic games",
            "Electronics[21]",
            "Embroidery[22]",
            "Engraving",
            "Entertaining",
            "Everyday carry",
            "Experimenting",
            "Fantasy sports",
            "Fashion",
            "Fashion design",
            "Feng shui decorating",
            "Filmmaking",
            "Fingerpainting",
            "Fishfarming",
            "Fishkeeping",
            "Flower arranging[23]",
            "Fly tying",
            "Foreign language learning[24]",
            "Furniture building",
            "Gaming (tabletop games, role-playing games,[25] Electronic games)",
            "Genealogy[26]",
            "Gingerbread house making",
            "Giving advice",
            "Glassblowing[27]",
            "Gardening",
            "Gongfu tea",
            "Graphic design",
            "Gunsmithing",
            "Hacking",
            "Hairstyle",
            "Hardware",
            "Herp keeping",
            "Home improvement",
            "Homebrewing[28]",
            "Homing pigeons",
            "Houseplant care[29]",
            "Hula hooping",
            "Hydroponics[30]",
            "Ice skating[31]",
            "Inventing",
            "Jewelry making[32]",
            "Jigsaw puzzles[33]",
            "Journaling",
            "Judo",
            "Juggling[34]",
            "Karaoke",
            "Karate",
            "Kendama",
            "Knife making",
            "Knitting[35]",
            "Knot tying",
            "Kombucha brewing",
            "Kung fu",
            "Lace making[36]",
            "Lapidary[37]",
            "Leather crafting",
            "Lego building[38]",
            "Livestreaming",
            "Listening to music[39]",
            "Listening to podcasts",
            "Lock picking",
            "Machining[40]",
            "Macrame[41]",
            "Magic[42]",
            "Makeup",
            "Manga",
            "Massaging",
            "Mazes (indoor/outdoor)",
            "Mechanics",
            "Meditation",
            "Memory training",
            "Metalworking",
            "Miniature art",
            "Minimalism",
            "Model building",
            "Modeling[43]",
            "Model engineering",
            "Music",
            "Nail art",
            "Needlepoint",
            "Origami[44]",
            "Painting[45]",
            "Pen Spinning",
            "Performance",
            "Pet sitting",
            "Philately",
            "Photography",
            "Pilates",
            "Pipes",
            "Piracy",
            "Planning",
            "Plastic art",
            "Playing musical instruments[46]",
            "Poetry",
            "Poi",
            "Pole dancing",
            "Postcrossing",
            "Pottery[47]",
            "Practical jokes",
            "Pressed flower craft",
            "Proofreading and editing",
            "Proverbs",
            "Public speaking",
            "Puppetry",
            "Puzzles[48]",
            "Pyrography",
            "Quilling",
            "Quilting[49]",
            "Quizzes",
            "Radio-controlled model playing",
            "Rail transport modeling",
            "Rapping",
            "Reading",
            "Recipe creation",
            "Refinishing",
            "Reiki",
            "Reviewing Gadgets",
            "Robot combat",
            "Rubik's Cube",
            "Scrapbooking[50]",
            "Scuba Diving",
            "Sculpting[51]",
            "Sewing[52]",
            "Shitposting",
            "Shoemaking",
            "Singing[53]",
            "Sketching[20]",
            "Skipping rope",
            "Slot car",
            "Soapmaking[54]",
            "Social media",
            "Speedrunning",
            "Spreadsheets",
            "Stamp collecting",
            "Stand-up comedy[55]",
            "Storytelling",
            "Stretching",
            "String Figures",
            "Stripping",
            "Sudoku",
            "Talking",
            "Taekwondo",
            "Tapestry",
            "Tarot",
            "Tattooing",
            "Taxidermy[56]",
            "Telling jokes",
            "Thrifting",
            "Upcycling",
            "Video editing",
            "Video game developing",
            "Video gaming[57]",
            "Video making",
            "VR Gaming",
            "Wargaming",
            "Watch making",
            "Watching documentaries",
            "Watching movies[58]",
            "Watching television",
            "Wax sealing",
            "Waxing",
            "Weaving",
            "Webtooning",
            "Weight training",
            "Welding",
            "Whittling",
            "Wikipedia editing",
            "Wine tasting",
            "Winemaking",
            "Witchcraft",
            "Wood carving[59]",
            "Woodworking[60]",
            "Word searches",
            "Worldbuilding[61]",
            "Wikipedia racing/Wikiracing",
            "Writing[62]",
            "Writing music",
            "Yo-yoing[63]",
            "Yoga[64]",
            "Zumba",
            "Outdoors and sports",
            "Air sports[65]",
            "Airsoft",
            "Amateur geology",
            "Amusement park visiting",
            "Archery[66]",
            "Auto detailing",
            "Automobilism",
            "Astronomy[67]",
            "Backpacking",
            "Badminton",
            "BASE jumping[68]",
            "Baseball[69]",
            "Basketball[70]",
            "Beachcombing",
            "Beekeeping[71]",
            "Birdwatching[72]",
            "Blacksmithing",
            "BMX[73]",
            "Board sports[74]",
            "Bodybuilding[75]",
            "Bus riding",
            "Camping",
            "Canoeing",
            "Canyoning",
            "Carrier pigeons",
            "Car riding",
            "Car tuning",
            "Caving",
            "City trip",
            "Climbing",
            "Composting",
            "Croquet",
            "Cycling",
            "Dairy Farming",
            "Dandyism",
            "Darts",
            "Dodgeball",
            "Dog training",
            "Dog walking",
            "Dowsing[76]",
            "Driving[77]",
            "Farming",
            "Fishing[78]",
            "Flag football[79]",
            "Flower growing",
            "Flying[80]",
            "Flying disc",
            "Flying model planes",
            "Foraging[81]",
            "Fossicking",
            "Freestyle football[82]",
            "Fruit picking",
            "Gardening[83]",
            "Geocaching[84]",
            "Ghost hunting[85]",
            "Gold prospecting",
            "Graffiti[86]",
            "Groundhopping",
            "Guerrilla gardening",
            "Gymnastics",
            "Handball[87]",
            "Herbalism",
            "Herping",
            "High-power rocketry",
            "Hiking[88]",
            "Hobby horsing",
            "Hobby tunneling",
            "Hooping[89]",
            "Horseback riding",
            "Hunting[90]",
            "Inline skating[91]",
            "Jogging[92]",
            "Jumping rope",
            "Karting",
            "Kayaking[93]",
            "Kite flying[94]",
            "Kitesurfing[95]",
            "Lacrosse[96]",
            "LARPing[97]",
            "Letterboxing[98]",
            "Lomography",
            "Longboarding",
            "Martial arts",
            "Magnet fishing",
            "Metal detecting[99]",
            "Motorcycling",
            "Meteorology",
            "Motor sports[100]",
            "Mountain biking[101]",
            "Mountaineering[102]",
            "Museum visiting",
            "Mushroom hunting/mycology[103]",
            "Netball[104]",
            "Noodling",
            "Nordic skating[105]",
            "Orienteering[106]",
            "Paintball[107]",
            "Paragliding",
            "Parkour[108]",
            "Photography[109]",
            "Pickleball",
            "Picnicking",
            "Podcast hosting",
            "Polo[110]",
            "Powerlifting",
            "Public transport riding",
            "Qigong",
            "Radio-controlled model playing",
            "Rafting[111]",
            "Railway journeys",
            "Railway modelling",
            "Rappelling[112]",
            "Renaissance fair",
            "Renovating",
            "Road biking",
            "Rock climbing[102]",
            "Rock painting",
            "Roller skating[113]",
            "Roundnet",
            "Rugby[114]",
            "Running[92]",
            "Safari",
            "Sailing[115]",
            "Sand art[116]",
            "Scouting",
            "Scuba diving[117]",
            "Sculling or rowing[118]",
            "Shooting[119]",
            "Shopping[120]",
            "Shuffleboard",
            "Skateboarding[121]",
            "Skiing[122]",
            "Skimboarding[123]",
            "Skydiving[124]",
            "Slacklining[125]",
            "Sledding",
            "Snorkeling",
            "Snowboarding[122]",
            "Snowmobiling",
            "Snowshoeing",
            "Soccer",
            "Stone skipping[126]",
            "Storm chasing",
            "Sun bathing",
            "Surfing[127]",
            "Survivalism",
            "Swimming[128]",
            "Table tennis playing",
            "Taekwondo[129]",
            "Tai chi[130]",
            "Tennis",
            "Thru-hiking",
            "Topiary",
            "Tourism",
            "Trade fair visiting",
            "Travel",
            "Unicycling",
            "Urban exploration[131]",
            "Vacation",
            "Vegetable farming",
            "Vehicle restoration[132]",
            "Videography",
            "Volleyball",
            "Volunteering",
            "Walking",
            "Water sports[133]",
            "Zoo visiting"
        ]
    end
    
end